[project]
name = "blog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Bryan Ponce", email = "poncebryan002@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "django>=6.1.1",
    "gunicorn>=26.2.0",
    "wagtail>=8.0",
    "wagtailcodeblock>=1.30.0.0",
]

[project.scripts]
blog = "blog:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
